language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - add-on
  - extra
before_script:
- chmod +x gradlew
script:
- ./gradlew :app:assembleRelease
before_install:
- gem install fir-cli
after_success:
- fir p app/build/outputs/apk/release/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"